import pytest

from app.github.diff import parse_diff
from app.pipeline.filter import filter_files


def diff_for(path, added=("x = 1",), status="modified"):
    body = "".join(f"+{ln}\n" for ln in added)
    return (
        f"diff --git a/{path} b/{path}\n--- a/{path}\n+++ b/{path}\n"
        f"@@ -0,0 +1,{len(added)} @@\n{body}"
    )


@pytest.mark.parametrize(
    "path,reason",
    [
        ("package-lock.json", "lock file"),
        ("web/yarn.lock", "lock file"),
        ("uv.lock", "lock file"),
        ("go.sum", "lock file"),
        ("static/app.min.js", "generated file"),
        ("api/user.pb.go", "generated file"),
        ("svc/x_pb2.py", "generated file"),
        ("tests/__snapshots__/a.snap", "generated file"),
        ("node_modules/lib/index.js", "vendored or build output"),
        ("web/dist/bundle.js", "vendored or build output"),
        ("vendor/lib.go", "vendored or build output"),
        ("logo.png", "binary file"),
        ("docs/manual.pdf", "binary file"),
    ],
)
def test_skipped_files(path, reason):
    res = filter_files(parse_diff(diff_for(path)))
    assert res.skipped == {path: reason}
    assert res.kept == []


@pytest.mark.parametrize("path", ["app/main.py", "src/index.ts", "docs/README.md", "distance.py"])
def test_normal_files_are_kept(path):
    res = filter_files(parse_diff(diff_for(path)))
    assert [f.path for f in res.kept] == [path]


def test_custom_ignore_globs_match_path_and_basename():
    text = diff_for("legacy/old.py") + diff_for("src/gen_types.py") + diff_for("src/ok.py")
    res = filter_files(parse_diff(text), ["legacy/*", "gen_*.py"])
    assert [f.path for f in res.kept] == ["src/ok.py"]
    assert set(res.skipped.values()) == {"ignored by .reviewly.yml"}


def test_generated_header_marker_is_detected():
    text = diff_for("src/api.py", ["# Code generated by protoc. DO NOT EDIT.", "x = 1"])
    assert filter_files(parse_diff(text)).skipped == {"src/api.py": "generated file"}


def test_deleted_file_is_skipped():
    text = "diff --git a/x.py b/x.py\ndeleted file mode 100644\n--- a/x.py\n+++ /dev/null\n@@ -1 +0,0 @@\n-a\n"  # noqa: E501
    assert filter_files(parse_diff(text)).skipped == {"x.py": "deleted file"}


def test_binary_and_pure_rename_are_skipped():
    text = "diff --git a/a.dat b/a.dat\nBinary files a/a.dat and b/a.dat differ\n"
    text += "diff --git a/x.py b/y.py\nrename from x.py\nrename to y.py\n"
    res = filter_files(parse_diff(text))
    assert res.skipped == {"a.dat": "binary file", "y.py": "no textual changes"}
